# Use Python 3.10 as the base image
ARG python_version=3.6
FROM python:${python_version}
LABEL maintainer="devs@bigchaindb.com"

# Install required system packages and dependencies
RUN apt-get update && \
    apt-get install -y vim build-essential python3-dev libffi-dev libssl-dev pkg-config libev-dev && \
    apt-get autoremove -y && \
    apt-get clean

# Upgrade pip and install Python dependencies
RUN pip install -U pip
RUN pip install "Cython>=0.29.21"

# Install specific versions of gevent and other libraries
RUN pip install "gevent==21.8.0"
RUN pip install "pynacl==1.2.0"
RUN pip install "rdflib==5.0.0"
RUN pip install "rdflib-jsonld==0.6.2"
RUN pip install  "pyshacl==0.16.2"  

ARG backend
ARG abci_status

# Set environment variables
ENV PYTHONUNBUFFERED=0 \
    BIGCHAINDB_DATABASE_PORT=27017 \
    BIGCHAINDB_DATABASE_BACKEND=$backend \
    BIGCHAINDB_SERVER_BIND=0.0.0.0:9984 \
    BIGCHAINDB_WSSERVER_HOST=0.0.0.0 \
    BIGCHAINDB_WSSERVER_SCHEME=ws \
    BIGCHAINDB_WSSERVER_ADVERTISED_HOST=0.0.0.0 \
    BIGCHAINDB_WSSERVER_ADVERTISED_SCHEME=ws \
    BIGCHAINDB_TENDERMINT_PORT=26657 \
    BIGCHAINDB_CI_ABCI=${abci_status}

# Set up the application directory
RUN mkdir -p /usr/src/app
COPY . /usr/src/app/
WORKDIR /usr/src/app

# Install the application in development mode
RUN pip install -e .[dev]

# Run BigchainDB configuration
RUN bigchaindb -l INFO -y configure
